---
# http://stackoverflow.com/questions/35153960/node-gyp-error-in-travis-build-for-node-4-0-4-1
language: node_js
node_js:
  - "4.2.4"
env:
  - CXX=g++-4.8
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-4.8enter code here
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
notifications:
   email: false
git:
  depth: 10
